from cmath import exp

from common.utils import print_header, print_toc_entry, print_sub_section
import numpy as np

def main(): 
    print_header("Day 1: Introduction to NumPy")
    print_toc_entry(1, "create numpy arrays using list and built-in functions")
    print_toc_entry(2, "array operations")
    print_toc_entry(3, "array indexing and slicing")

    print_sub_section(1, "create numpy arrays using list and built-in functions")
    # Create a 1D array
    num_list: list[int] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    array_1d = np.array(num_list)
    print("numpy array created from list:")
    print(array_1d)
    
    print("\ncreate numpy array using built-in functions:")
    print("\nnumpy array of ones:")
    ones = np.ones(5)  
    print(ones)
    print("\nnumpy array of 2 by 4 of ones:")
    two_by_four = np.ones((2, 4))
    print(two_by_four)
    zeroes = np.zeros(5)
    print("numpy array of zeroes:")
    print(zeroes)
    matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
    print("\nnumpy array created from matrix:")
    print(matrix)
    print("\nnumpy array of zeroes using 3 x 3 matrix:")
    zeroes_matrix = np.zeros([3,3])
    print(zeroes_matrix)
    print("\nnumpy array of ones using 3 x 3 matrix:")
    ones_matrix = np.ones([1, 1])
    print(ones_matrix)
    print("\nnumpy array using arange:")
    range_array = np.arange(0, 20, 2)
    print(range_array)
    print("\nnumpy array using linsapce:")
    linspace_array = np.linspace(0, 1, 25)
    print(linspace_array)
    print("\nnumpy array using reshape:")
    reshaped_array1 = np.reshape([0, 1, 2, 3 , 4, 5],(2, 3))
    arr1  = np.array ([0, 1, 2, 3 , 4, 5])
    reshaped_array2 = arr1.reshape(2, 3)
    print(reshaped_array1)
    print(reshaped_array2)
    print("\nnumpy adding new dimensions:")
    default_array = np.array([0, 1, 2, 3, 4, 5])
    expanded_array = default_array[:, np.newaxis]
    print(expanded_array)
    print_header("Basic Operations on NumPy Arrays")
    print_toc_entry(1, "Element-wise operations")
    print_toc_entry(2, "Mathematical operations")
    
    print_sub_section(1, "Element-wise operations")
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    print("a + b =", a + b)
    print("a - b =", a - b)
    print("a * b =", a * b)
    print("a / b =", a / b)
    print("\na ** b =", a ** b)
    
    print_sub_section(2, "Mathematical operations")
    math_array = np.array([4, 9, 25, 49, 64, 81, 100, 16, 36, 36])
    print("Square root:", np.sqrt(math_array))
    print("Exponential:", np.exp(math_array))  
    print("Logarithm:", np.log(math_array))
    print("mean:", np.mean(math_array))  
    print("median:", np.median(math_array))
    print("mode:", np.bincount(math_array.astype(int)).argmax())
    print("standard deviation:", np.std(math_array))
    print("variance:", np.var(math_array))
    print("sum:", np.sum(math_array))
    print("cumulative sum:", np.cumsum(math_array))
    print("min:", np.min(math_array))
    print("max:", np.max(math_array))
    
    print_sub_section(3, "array indexing, slicing and reshaping")
    arr_index = np.array([10, 20, 30, 40, 50, 60])
    print("Original array:", arr_index)
    print("Element at index 2:", arr_index[2])
    print("Slicing from index 1 to 3:", arr_index[1:4])
    print("Slicing from start to index 2:", arr_index[:2])
    print("Slicing from index 3 to end:", arr_index[3:])
    print("Slicing with step of -2:", arr_index[-2])
    print("Slicing with step of 2:", arr_index[::2])
    print("Reversing the array:", arr_index[::-1])
    print("\nReshaping the array:")
    reshaped_array = arr_index.reshape(2, 3)
    print("reshaped array:\n", reshaped_array)


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    main()

